
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fgpsfqjellkukgnqhmdh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZncHNmcWplbGxrdWtnbnFobWRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzMDI5MjEsImV4cCI6MjA2MTg3ODkyMX0.6mo95QL84cLRx8HZA7F0yM5yjoWF39tQ8i96XZLL9CM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      autoRefreshToken: true,
      persistSession: true,
      detectSessionInUrl: true,
      flowType: 'implicit',
    }
  }
);

// Verifica se a sessão foi carregada corretamente
supabase.auth.onAuthStateChange((event, session) => {
  console.log('Evento de autenticação:', event);
  console.log('Sessão atual:', session);
});
