
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fgpsfqjellkukgnqhmdh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZncHNmcWplbGxrdWtnbnFobWRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzMDI5MjEsImV4cCI6MjA2MTg3ODkyMX0.6mo95QL84cLRx8HZA7F0yM5yjoWF39tQ8i96XZLL9CM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      autoRefreshToken: true,
      persistSession: true,
      detectSessionInUrl: true,
      flowType: 'implicit',
      storage: localStorage, // Garantindo que o localStorage é usado explicitamente
    }
  }
);

// Verificação detalhada da sessão e eventos de autenticação
supabase.auth.onAuthStateChange((event, session) => {
  console.log('Evento de autenticação:', event);
  console.log('Detalhes da sessão:', session ? {
    user: session.user?.email,
    auth_token: session.access_token ? 'Presente' : 'Ausente',
    refresh_token: session.refresh_token ? 'Presente' : 'Ausente',
    expires_at: session.expires_at
  } : 'Sem sessão');
});

// Verificação inicial da sessão no carregamento
supabase.auth.getSession().then(({ data, error }) => {
  if (error) {
    console.error('Erro ao verificar sessão:', error);
  } else {
    console.log('Status da sessão inicial:', data.session ? 'Autenticado' : 'Não autenticado');
  }
});
